"""Runtime configuration for the local language-model provider.

Clippy can use the bundled Ollama workflow, but it should not require every
user to download several gigabytes of models.  This module keeps the provider
choice in one small JSON file and also supports environment variables for
packaged deployments and power users.

The supported providers are:

* ``ollama`` - the existing local Ollama HTTP API.
* ``openai_compatible`` - local or hosted APIs exposing OpenAI chat and vision completions.
* ``gemini_api`` - Google's supported OpenAI-compatible Gemini API.
* ``codex_cli`` - the authenticated Codex CLI using a ChatGPT account.
* ``claude_cli`` - the authenticated Claude Code CLI using a Claude plan.

Embeddings are generated by the bundled MiniLM runtime and never use the
selected provider.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any

from core.cli_providers import is_cli_provider, provider_defaults

try:
    from core.paths import get_data_dir
except ImportError:
    from paths import get_data_dir


LOCAL_EMBEDDING_MODEL = "local:sentence-transformers/all-MiniLM-L6-v2"
GEMINI_API_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai"
GEMINI_DEFAULT_MODEL = "gemini-2.5-flash"

DEFAULT_CONFIG: dict[str, str] = {
    "provider": "ollama",
    "base_url": "http://127.0.0.1:11434",
    "api_key": "",
    "cli_command": "",
    "chat_model": "qwen3:8b",
    "vision_model": "qwen3-vl:4b",
    "embedding_model": LOCAL_EMBEDDING_MODEL,
}

CONFIG_FILENAME = "llm_config.json"
_PROVIDER_ALIASES = {
    "ollama": "ollama",
    "openai": "openai_compatible",
    "openai-compatible": "openai_compatible",
    "openai_compatible": "openai_compatible",
    "local": "openai_compatible",
    "local-api": "openai_compatible",
    "local_api": "openai_compatible",
    "codex": "codex_cli",
    "codex-cli": "codex_cli",
    "codex_cli": "codex_cli",
    "claude": "claude_cli",
    "claude-code": "claude_cli",
    "claude_cli": "claude_cli",
    "gemini": "gemini_api",
    "gemini-api": "gemini_api",
    "gemini_api": "gemini_api",
    "gemini-cli": "gemini_api",
    "gemini_cli": "gemini_api",
}
_STRING_FIELDS = {
    "base_url",
    "api_key",
    "cli_command",
    "chat_model",
    "vision_model",
    "embedding_model",
}
_ENV_FIELDS = {
    "provider": "CLIPPY_LLM_PROVIDER",
    "base_url": "CLIPPY_LLM_BASE_URL",
    "api_key": "CLIPPY_LLM_API_KEY",
    "cli_command": "CLIPPY_CLI_COMMAND",
    "chat_model": "CLIPPY_CHAT_MODEL",
    "vision_model": "CLIPPY_VISION_MODEL",
}


def get_config_path() -> Path:
    return get_data_dir() / CONFIG_FILENAME


def _clean_url(value: Any, default: str) -> str:
    url = str(value or default).strip().rstrip("/")
    if not url:
        url = default
    if len(url) > 500:
        raise ValueError("LLM base URL is too long.")
    if any(character.isspace() for character in url):
        raise ValueError("LLM base URL cannot contain whitespace.")
    if not (url.startswith("http://") or url.startswith("https://")):
        raise ValueError("LLM base URL must start with http:// or https://.")
    return url


def _clean_text(value: Any, field: str, default: str, *, required: bool = False) -> str:
    text = str(value if value is not None else default).strip()
    if required and not text:
        raise ValueError(f"{field} cannot be empty.")
    if len(text) > 240:
        raise ValueError(f"{field} is too long.")
    return text


def normalize_config(values: dict[str, Any] | None = None) -> dict[str, str]:
    """Return a validated, canonical provider configuration.

    ``values`` is intentionally permissive so it can consume old or hand-
    edited config files. Unknown keys are discarded before persistence.
    """

    source = dict(DEFAULT_CONFIG)
    if values:
        source.update({key: value for key, value in values.items() if key in DEFAULT_CONFIG})

    raw_provider = str(source.get("provider") or DEFAULT_CONFIG["provider"]).strip().lower()
    provider = _PROVIDER_ALIASES.get(raw_provider)
    if not provider:
        raise ValueError("Unsupported provider.")

    if is_cli_provider(provider):
        base_url = "cli://local"
        default_chat, default_vision = provider_defaults(provider)
        chat_value = source.get("chat_model")
        vision_value = source.get("vision_model")
        if chat_value in {"", "qwen3:8b", None}:
            chat_value = default_chat
        if vision_value in {"", "qwen3-vl:4b", None}:
            vision_value = default_vision
    else:
        default_url = (
            GEMINI_API_BASE_URL
            if provider == "gemini_api"
            else "http://127.0.0.1:1234/v1"
            if provider == "openai_compatible"
            else DEFAULT_CONFIG["base_url"]
        )
        configured_url = source.get("base_url")
        if provider == "gemini_api" and (
            not values
            or "base_url" not in values
            or raw_provider in {"gemini-cli", "gemini_cli"}
            or configured_url in {"cli://local", DEFAULT_CONFIG["base_url"]}
        ):
            configured_url = GEMINI_API_BASE_URL
        base_url = _clean_url(configured_url, default_url)
        chat_value = source.get("chat_model")
        vision_value = source.get("vision_model")
        if provider == "gemini_api":
            if chat_value in {"", "auto", "qwen3:8b", None}:
                chat_value = GEMINI_DEFAULT_MODEL
            if vision_value in {"", "auto", "qwen3-vl:4b", None}:
                vision_value = GEMINI_DEFAULT_MODEL



    config = {
        "provider": provider,
        "base_url": base_url,
        "api_key": _clean_text(source.get("api_key"), "api_key", ""),
        "cli_command": _clean_text(source.get("cli_command"), "cli_command", ""),
        "chat_model": _clean_text(chat_value, "chat_model", DEFAULT_CONFIG["chat_model"], required=True),
        "vision_model": _clean_text(vision_value, "vision_model", DEFAULT_CONFIG["vision_model"], required=True),
        "embedding_model": LOCAL_EMBEDDING_MODEL,
    }
    return config


def _read_saved_config() -> dict[str, Any]:
    path = get_config_path()
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return payload if isinstance(payload, dict) else {}
    except (OSError, ValueError) as exc:
        print(f"[llm-config] ignored invalid config: {exc}")
        return {}


def get_llm_config() -> dict[str, str]:
    """Load the current config, with environment variables taking precedence."""

    values: dict[str, Any] = dict(DEFAULT_CONFIG)
    values.update(_read_saved_config())
    for field, env_name in _ENV_FIELDS.items():
        env_value = os.environ.get(env_name)
        if env_value is not None and env_value.strip():
            values[field] = env_value
    try:
        return normalize_config(values)
    except ValueError as exc:


        print(f"[llm-config] falling back to defaults: {exc}")
        return normalize_config(DEFAULT_CONFIG)


def save_llm_config(values: dict[str, Any]) -> dict[str, str]:
    """Merge and atomically persist user-editable provider settings."""

    current = get_llm_config()
    merged = dict(current)
    if "provider" in values and "base_url" not in values:
        target_provider = _PROVIDER_ALIASES.get(str(values["provider"]).strip().lower())
        if target_provider and target_provider != current["provider"]:
            merged["base_url"] = (
                GEMINI_API_BASE_URL
                if target_provider == "gemini_api"
                else "http://127.0.0.1:1234/v1"
                if target_provider == "openai_compatible"
                else "cli://local"
                if is_cli_provider(target_provider)
                else DEFAULT_CONFIG["base_url"]
            )
    for key in DEFAULT_CONFIG:
        if key in values:
            merged[key] = values[key]
    config = normalize_config(merged)

    path = get_config_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{CONFIG_FILENAME}.", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(config, handle, indent=2)
            handle.write("\n")
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
    return get_llm_config()


def public_llm_config(config: dict[str, str] | None = None) -> dict[str, Any]:
    """Return safe-to-display settings without exposing the API key."""

    current = normalize_config(config or get_llm_config())
    return {
        **{key: value for key, value in current.items() if key != "api_key"},
        "api_key_set": bool(current.get("api_key")),
        "environment_overrides": [
            field
            for field, env_name in _ENV_FIELDS.items()
            if (os.environ.get(env_name) or "").strip()
        ],
    }


def model_for(role: str, fallback: str | None = None) -> str:
    config = get_llm_config()
    field = {
        "chat": "chat_model",
        "vision": "vision_model",
        "embedding": "embedding_model",
        "embed": "embedding_model",
    }.get(role, "chat_model")
    return config.get(field) or fallback or DEFAULT_CONFIG[field]


def is_external_provider(config: dict[str, str] | None = None) -> bool:
    return normalize_config(config or get_llm_config())["provider"] != "ollama"
